### ISSUE TITLE
2.0 version is awesome

### ISSUE THREAD

**Issue by nurdt** [amirzaidi/Launcher3#113]
on Nexus 5x everything but app suggestion is great

**Comment by cavon08** [comment]
I agree! Thanks Amir, fantastic job!!

**Comment by shiva39** [comment]
I want that version send me that link

On Aug 25, 2017 7:08 AM, "cavon08" <notifications@github.com> wrote:

I agree! Thanks Amir, fantastic job!!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/amirzaidi/Launcher3/issues/113#issuecomment-324801180>,
or mute the thread

**Comment by amirzaidi** [comment]
@shiva39 check the releases section :)

**Comment by shiva39** [comment]
Send that launcher link 2.0.1 version

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
