### ISSUE TITLE
2.0.1 touches perfection!

### ISSUE THREAD

**Issue by madvinegar** [amirzaidi/Launcher3#114]
Many many thanks for your hard work. The result is outstanding.
In my s7 edge (non rooted, android 7.0 stock) everything works great. I have installed Launcher 2.0.1 and I don't get the ghost popup when an app shortcut bubble closes. I do have this circle shadow when opening the drawer but I don't mind at all. It looks like a feature!

Notification badges work great.
Weather widget works greats.
Google drawer works great.
Sliding down for the top panel to drop works great.

If you also manage to backport the long-press app shortcuts for android 7.0 (or less), I believe that it would be the perfect replacement for Pixel Launcher for non-rooted phones. 

Keep up the good work!

**Comment by shiva39** [comment]
Send me that link

On Aug 25, 2017 11:26 AM, "madvinegar" <notifications@github.com> wrote:

Many many thanks for your hard work. The result is outstanding.
In my s7 edge (non rooted, android 7.0 stock) everything works great. I
have installed Launcher 2.0.1 and I don't get the ghost popup when an app
shortcut bubble closes. I do have this circle shadow when opening the
drawer but I don't mind at all. It looks like a feature!

Notification badges work great.
Weather widget works greats.
Google drawer works great.
Sliding down for the top panel to drop works great.

If you also manage to backport the long-press app shortcuts for android 7.0
(or less), I believe that it would be the perfect replacement for Pixel
Launcher for non-rooted phones.

Keep up the good work!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/amirzaidi/Launcher3/issues/114>, or mute the thread

**Comment by amirzaidi** [comment]
Circle shadow will be fixed in a few minutes thanks to @deletescape!

**Comment by RikKoedoot** [comment]
What was wrong with them?
Op vr 25 aug. 2017 om 12:49 schreef Amir Zaidi <notifications@github.com>

**Comment by madvinegar** [comment]
I remember that I firstly installed the 2.0 version that did not have the circle shadow when opening a folder, but had the annoying ghost popup when an app shortcut bubble closes.

Version 2.0.1, had the circle shadow (which I don't particularly mind), but did not have the annoying ghost popup when an app shortcut bubble closes, so this is why I stuck with 2.0.1

Now, you say version 2.0.2 does not have the circle shadow, but does it have the ghost bubble...?


EDIT: It doesn't, all is working fine!

Next stop, app shortcuts for 7.0 android... :D
