### ISSUE TITLE
Can't change lockscreen wallpaper

### ISSUE THREAD

**Issue by Pinzauti** [amirzaidi/Launcher3#120]
If i try to change the wallpaper from the launcher options, and i choose to select the image from Google Photo, it doesn't ask me if i want to change the wallpaper also for the lockscreen but it changes the wallpaper automatically for the home only.
It works instead if i pick the photo from Google Now Launcher.
Device: Moto G4
Android version: 7.0 Nougat

**Comment by amirzaidi** [comment]
Install Google Wallpapers from the Play Store, then try changing it through the launcher

**Comment by Pinzauti** [comment]
After installing Google Wallpaper everything works fine

**Comment by Pinzauti** [comment]
I think that is a feature that should be enabled by default without the need to install an external app, or at least it would be cool showing a message saying that the app is required in order to use the launcher. My two cents.

**Comment by amirzaidi** [comment]
It is in my Reddit post FAQ, I just wished people bothered to read everything I wrote instead of having to answer the same thing many times

**Comment by Pinzauti** [comment]
Dear, If you feel stressed try to go outside, eat something and then try to be more polite. And if that doesn't work, there are lot of psychiatrist out there.

Not everyone who download and uses the launcher is a developer, uses Github, reads Reddit and so on.
In the past two days the launcher was linked by several blog and downloaded directly by people who have no idea who you are and what Github is. My suggestion was in order to help those people, the majority of the users by the way.

And by the way, there is no link to Reddit FAQ here.

Everyone is here to help you developing something great, despite your bad character and your social problems.
Try to show some respect.
Thank you.

**Comment by RikKoedoot** [comment]
Dont be so rude to him. He is the One that spends all day making this
possible. And then you come and show no respect. You dont even know how
much effort he puts into this app so you can Just download it and install
it Without being to hard.
Try to show some respect
Thank you, retard.
Op zo 27 aug. 2017 om 08:15 schreef Francesco Pinzauti <
notifications@github.com>

**Comment by amirzaidi** [comment]
> And by the way, there is no link ti Reddit FAQ here.

The Reddit link is actually on the Releases tab under the 2.0 version. I can't help it that blogs don't include all the necessary information, but if they don't read MY full post and only read the blog, then complain they didn't get the necessary information ("or at least it would be cool showing a message saying that the app is required in order to use the launcher") it makes me very annoyed. It's a "feature" that you are able to use this app without Google Wallpapers installed, the regular Pixel Launcher forces you to install the app to even change the wallpaper.

> despite your bad character and your social problems

I try very hard to be respectful to others but days and days of hard work and then having many users that don't bother reading what I wrote can make me lose my temper sometimes. Sorry about the tone of my previous message.
