### ISSUE TITLE
Nothing on setting except rotation!

### ISSUE THREAD

**Issue by Princepritam1994** [amirzaidi/Launcher3#134]
Hi first of all thank you for awesome launcher it is working very well on my K6 power which is running on nougat 7.0. Well I have found that when I head to settings there is no option except the screen rotation option on homescreen. No option to change icons. Please fix that.

**Comment by SeBsZ** [comment]
I had the same issue, but I fixed it by again uninstalling Launcher3 from the app settings list first (make sure to set another app the homescreen app first) and then make sure you download the correct version again v2.1. I noticed it was installed correctly the second time because I saw the new app icon, a prompt to allow notification access and all the settings are there now. So just some friendly advice - try reinstalling and ensure you're installing the latest APK, and not an older download. One of these solved the problem for me - I was sure I had installed the latest version... apparently not.

**Comment by Aziir** [comment]
I have the same problem only screen rotacion setting. My android : 6.0.1

**Comment by amirzaidi** [comment]
Only the rotation shows up on Android 7 and lower, this is normal. All the features are still working. It's just the way the settings work that ties in with the Android 8 system

**Comment by Princepritam1994** [comment]
Not solved bro. I reinstalled it. But no luck.

**Comment by suphon-t** [comment]
@Princepritam1994 please read the comment right above yours.
