### ISSUE TITLE
Hide Google Now Launcher Icon

### ISSUE THREAD

**Issue by acsh90** [amirzaidi/Launcher3#15]
Is it possible to hide the "Google now launcher" icon in app drawer?
Can't uninstall on Nexus 6P.

**Comment by amirzaidi** [comment]
Compile the app yourself and add it to https://github.com/amirzaidi/Launcher3/blob/master/src/com/android/launcher3/SuperNexusAppFilter.java

**Comment by acsh90** [comment]
I don't know how... is it possible to add that for your next version 1.3 please?

**Comment by amirzaidi** [comment]
No, because other users might want to see it in their app drawer to easily uninstall it.

**Comment by Trak-X** [comment]
@amirzaidi compiling should be done with Android Studio? or other tools? 

Thank you for this great port!

**Comment by acsh90** [comment]
There is really no point being in app drawer. 
When people fresh install a launcher, they have to choose "once or always" when pressed home, so they know they are going to decide on a launcher.
Please consider hiding it, it's kind annoying to be there as it does nothing at all.

**Comment by amirzaidi** [comment]
I don't want to hide apps on user request, because not everyone agrees to the preferences of what should be hidden. If you truly want it hidden do it yourself and make your own builds.

@Trak-X yes, I simply compile the compat branch with Android Studio. The master branch should also work if you're not on a custom ROM.
