### ISSUE TITLE
Settings options dissapeared and some other stuff too

### ISSUE THREAD

**Issue by efeboAbel** [amirzaidi/Launcher3#179]
on android 6.0.1, dirty unicorns, when i maintain  pressing i expect the wallpaper, widget and settings must appear, but on android 6.0.1 settings is not available, on android 7.1.2 it is but only one option available the rotation option, the most recent used apps are no longer listed in the drawer, the drawer icon can be changed but not those on the desktop, those are unaltered using pixel settings app and pixel icon pack

**Comment by lucasdeeiroz** [comment]
+1 on that. I'm on AOSP 7.1.2 and only rotation option is available. I did have official Pixel Launcher 
 and Pixel Icons installed via OpenGAPPS before installing Launcher3, I don't know if it's related.

**Comment by abdullahibneat** [comment]
1. Try clearing app data and cache for Launcher3. 

2. You only see one option in settings because you don't have Android Oreo (other settings are related to notification dots and icon shape).

3. The App Suggestion feature had not been implemented as it requires too much work for one single feature. 

4. This launcher has not been optimised for icon packs. I'd suggest to use Lawnchair (another Pixel launcher) for more customisation.

Hope that helps!

**Comment by efeboAbel** [comment]
Hi @abdullahibneat , thanks for replying , as you explained, it seems that nothing  is wrong with version 2.1 after all, the version 1.5 allowed to customize the desktop icons , i can live with that, as long i have google now integration when i swipe right Launcher3 (Rootless Pixel Launcher) 

The XDA article didn't explain properly that the extra options were only available if you had oreo installed, but with your explanation now i have no complains at all, maybe i use the sidebar that comes along with DirtyUnicorns Rom to access the most frequent apps 

regards

**Comment by abdullahibneat** [comment]
If you're happy, you may close this issue. You may also want to have a read to issue #133 and issue #147.
