### ISSUE TITLE
Pull down  notification from anywhere in the home screen doesn't work in Android 6

### ISSUE THREAD

**Issue by samirmz** [amirzaidi/Launcher3#186]
Pull down  notification from anywhere in the home screen doesn't work in Android 6.
Device: Samsung galaxy J710

**Comment by RikKoedoot** [comment]
Maybe the method used doesn't work on 6.0

**Comment by abdullahibneat** [comment]
I believe this feature works from Android Nougat and above, let's wait for amir.

**Comment by amirzaidi** [comment]
It should work on any Android phone from lollipop onwards, but it might be a Samsung specific bug because they change the API. Would need to see the Touchwiz framework to figure out the method calls on Samsung phones:

https://github.com/amirzaidi/Launcher3/blob/680e21cf07ffff5088fe3343e007861592d8866a/src/com/android/launcher3/Launcher.java#L1960

**Comment by NathanFrederick** [comment]
My phone is Android 6 and the pull down notification works anywhere on my home screen it works for me

**Comment by damtur** [comment]
On One Plus 5T it doesn't work either. It's running android 7.1.1

**Comment by damtur** [comment]
I've downloaded the latest version and it works fine.
