### ISSUE TITLE
resize widgets without restrictions

### ISSUE THREAD

**Issue by oligafner** [amirzaidi/Launcher3#187]
## Description
Some widgets have a defined minimal width and height, so you can't make them smaller. Is it possible to allow the resizing always by default? I think there is really no downside to implement that change since it doesn't require a setting or forces the user to do something different than with the AOSP version of the launcher

## Expected Behavior
Launcher should ignore the min width/height of widget and allow user to scale them smaller

## Actual Behavior
Launcher doesn't ignore the min width/height of widget and doesn't allow the user to scale them smaller than their min size.

## Steps to Reproduce
1. Drag a widget with min width/height on the homescreen.
2. Try to resize it to a 1x1 square.
3. Sadly, doesn't work.
4. Should though ;)

## Environment
* Device: Motorola Moto Z Play RETEU
* Android version: 7.1.1
* Launcher version: 2.1
* Rom: Stock

**Comment by RikKoedoot** [comment]
Good issue post. Lets wait for what amir has to say

**Comment by amirzaidi** [comment]
> Launcher should ignore the min width/height of widget and allow user to scale them smaller

That's not expected behaviour, that would actually be a bug.
If you want to turn this off:

src/com/android/launcher3/AppWidgetResizeFrame.java 
change
mResizeMode = info.resizeMode;
to
mResizeMode = AppWidgetProviderInfo.RESIZE_BOTH;

and

mMinHSpan = info.minSpanX;
mMinVSpan = info.minSpanY;
to
mMinHSpan = 1;
mMinVSpan = 1;

**Comment by oligafner** [comment]
thanks for your help though
