### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by ghost** [amirzaidi/Launcher3#190]
Only one setting is available on the launcher setting page, just the Home screen rotation, I use Android 6

**Comment by Malwick22** [comment]
I've got the same problem, too. And i'm running on nougat 7.0. Let's just wait for amir.

**Comment by samirmz** [comment]
Me too has same issue in Android 6 ( Samsung Galaxy J7)

**Comment by RikKoedoot** [comment]
Cant you Just read the readme faq "I only have on option in the settings
menu

This is normal, only Android 8 users can see the other options.
Notification dots are always enabled on Android 6 & 7"
Op wo 30 aug. 2017 om 06:54 schreef samirmz <notifications@github.com>

**Comment by RikKoedoot** [comment]
Someone close this one please
Op wo 30 aug. 2017 om 08:10 schreef Rick Kode <rickkode@gmail.com>

**Comment by ghost** [comment]
Thank you Rickkode, but let amir tell us if he's back porting it, this is Android where everything is possible ☺️☺️☺️

**Comment by RikKoedoot** [comment]
Everything is enabled by default if your Android supports it. 7.1 or above you get full feature set

**Comment by ghost** [comment]
Let Amir come tell us it's impossible or are you hours spokesperson?

**Comment by amirzaidi** [comment]
Rik is allowed to answer on my behalf, if he is wrong I'll comment on it. Yes, the settings will not be backported, but they are **enabled by default**. It is because they overwrite Android 8 properties that do not exist on older versions. Changing this behaviour would cause many unexpected bugs so I'm keeping it as is.
