### ISSUE TITLE
Icon related

### ISSUE THREAD

**Issue by khemu111** [amirzaidi/Launcher3#193]
I have redmi note 4 on android 7.0  before this launcher3 my icons look good but after this my icon looks like old phones

**Comment by RikKoedoot** [comment]
Send a screenshot otherwise amir can't know what you ment

**Comment by luminousmazim** [comment]
Maybe he mean is white rounded icon background. I have this problem too, using los 14.1. Actually, it's not the problem but just i prefer the default one. Can i change the icon to default?

**Comment by amirzaidi** [comment]
The round icons are part of the Pixel experience so I went through the trouble of backporting them with a XML hack :(

You can remove them from the DynamicIconProvider.java

**Comment by luminousmazim** [comment]
Can give me a hint which line i must remove?

That's fine, if i can do it myself so be it. Most people here seems like this rounded icon, but for me it just weird because most of my icon is not rounded (default). Some icon are great like outlook icon but the white background... No no.

The dot featue is supposed to be just blank dot, no notification counter? If this was a feature in default pixel laucher, i found this weird.

But anyway, thanks for this great launcher. Much better than trebuchet of course.

**Comment by khemu111** [comment]
![img_20170831_093309](https://user-images.githubusercontent.com/31464507/29905990-72ce67f6-8e2f-11e7-940e-1b9b54497118.jpg)
Look these diler or massage icons they are look like old

**Comment by khemu111** [comment]
Without this launcher my icons look good and fine blue finishing

**Comment by lintangwahyu** [comment]
That is the stock icon from xiaomi , i have the same phone to . Hopefully for adding icon style feature , like teardrops .

**Comment by lintangwahyu** [comment]
and support with 3rd party icon pack

**Comment by ivanosh** [comment]
For supporting 3rd party icon packs, you can use one of 100 customizable launcher from the store. This one is pure and without any extra-shit
