### ISSUE TITLE
Sesame Integration 

### ISSUE THREAD

**Issue by SethuSenthil** [amirzaidi/Launcher3#219]
Launchers like Nova launcher has [Sesame](https://play.google.com/store/apps/details?id=ninja.sesame.app.edge) integration and many people found this to be extremely useful and since the launcher already supports shortcuts and notification dots wouldn't this be a great addition?

**Comment by AndreHM** [comment]
But the launcher is Pixel Launcher, it's better to have something more pure in memory.

**Comment by abdullahibneat** [comment]
Unfortunately this launcher has been developed with a stock experience in mind. Since the stock Pixel Launcher doesn't have this integration, RPL won't either. However, since this is an open source project you can add the integration and compile your own launcher.

You may close the issue if your happy to do so.
