### ISSUE TITLE
nothing changes

### ISSUE THREAD

**Issue by priincekissed** [amirzaidi/Launcher3#23]
really nothing 😊

**Comment by amirzaidi** [comment]
Set it as your default launcher.

**Comment by priincekissed** [comment]
done already,still transparent app drawer, it says that the version is 1.2 but on my app setting v1.0

**Comment by amirzaidi** [comment]
Yes, that is because I do not manually update that version number to keep my commit history clean and easy to revert. It's also easier for testing, because you can revert to older versions without resetting. Do not worry about the version number.

The transparent app drawer seems to be a Marshmallow issue as far as I know, could you confirm you're on Lollipop or Marshmallow?

**Comment by priincekissed** [comment]
lollipop sir

**Comment by priincekissed** [comment]
please make it better than the original
