### ISSUE TITLE
Navigation buttons Moto G4/And the rest

### ISSUE THREAD

**Issue by userNeptune** [amirzaidi/Launcher3#242]
At the time of choosing the widget via shortcut the virtual buttons do not turn black and neither in the list of apps, you can change that l.
thanks ;)

**Comment by RikKoedoot** [comment]
that is only possible in Android Oreo, and g4 doesn't get that (sad), it's an Oreo api

**Comment by userNeptune** [comment]
so when you upgrade it will change on its own

**Comment by MrLuckas** [comment]
so when you upgrade it will change on its own

**Comment by MrLuckas** [comment]
so when you upgrade it will change on its own

**Comment by RikKoedoot** [comment]
@MrLuckas probably yes, and the update is coming, but may take a while

**Comment by ceholland2** [comment]
STOP

Sent from my Fire

On September 19, 2017, at 12:46 AM, rickkode <notifications@github.com> wrote:

@MrLuckas probably yes, and the update is coming, but may take a while

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/amirzaidi/Launcher3","title":"amirzaidi/Launcher3","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/amirzaidi/Launcher3">https://github.com/amirzaidi/Launcher3</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rickkode in #242: @MrLuckas probably yes, and the update is coming, but may take a while"}],"action":{"name":"View Issue","url":"<a href="https://github.com/amirzaidi/Launcher3/issues/242#issuecomment-330435886">https://github.com/amirzaidi/Launcher3/issues/242#issuecomment-330435886</a>"}}}
