### ISSUE TITLE
Just wondering

### ISSUE THREAD

**Issue by nikkomercado** [amirzaidi/Launcher3#284]
When do you think you'll be ready?

Like, you know.

To modify the new launcher and stuff.

Don't need he exact date but we just wanna know, like, will it be this year or next year or next 17 months.

Just give us a sign, Lord Amir.

**Comment by masiama** [comment]
At least when will be available new release? Last was in August

**Comment by RikKoedoot** [comment]
Just be patient, amir is busy with school, he doesn't have much time to work on the launcher

**Comment by amirzaidi** [comment]
I have already been looking at the sources this week but they changed so much in the new Pixel 2 Launcher version compared to AOSP's Launcher3 that I think it might be better to wait until Google upstreams it, which will probably happen for the 8.1 release

**Comment by amirzaidi** [comment]
https://github.com/amirzaidi/Launcher3/commit/bf47a1024a1e511184f734b796b19ca3b394034e
I've spent all afternoon and evening rushing and trying to make some progress on the Pixel 2 version but because Google hasn't released the Launcher3 sources porting that is on another level, I'm not anywhere near done yet and look at the amount of sources I've already had to change..

**Comment by bushman1** [comment]
Thanks Amir for the information. good to know that the project is not abondoned

**Comment by carloszapruder** [comment]
Love this launcher man!

Il 12 nov 2017 10:21 AM, "bushman1" <notifications@github.com> ha scritto:
