### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Thrilleratplay** [amirzaidi/Launcher3#33]
I found this on Github's tending list.  Could a basic README file be added to the root of the project either with a link to the development thread on XDA/Reddit/whatever or a small description explaining what the differences are between this launcher and the base project (AOSP Launcher3 I am guessing)?

**Comment by 92lleo** [comment]
Sorry for bringing this Issue up again right after you closed it, but I was searching for the Readme quite a while since it's only in the "o" branch. 
It would be good to merge it into master and keep it up to date there (or at least reference the readme in the other branch), cause thats the branch users see when viewing the repo.
