### ISSUE TITLE
Cannot swipe away stories in feed

### ISSUE THREAD

**Issue by guacamoly** [amirzaidi/Launcher3#337]
I'm not sure if this is a feature or a bug, but on the galaxy s7 I am not able to dismiss stories in the feed by swiping them to the right. I am able to do so in the feed from the google now launcher. 
I have to use the menu icon on each story to dissmiss it. Anyone else experiencing the same thing?

**Comment by jeromelefeuvre** [comment]
Same problem, same question on S8 !?

**Comment by mooshake13** [comment]
It's a feature Google introduced in newer versions of the app. It works in Google now launcher but otherwise if you need to dismiss, you simply have to click the 3 dots on top right and select done with this card.

Check this out:
https://www.droid-life.com/2017/08/17/google-now-feed-loses-card-swiping-nerds-losing-minds/

**Comment by jeromelefeuvre** [comment]
You can remove "simple" from your answer, LOL ;)

Anyways, thanks for the information !

**Comment by mooshake13** [comment]
Typo! Soz. Its 1 am here. I think i should hit the sack! Hah

**Comment by mooshake13** [comment]
Corrected. Thanks for pointing it out. 👍
