### ISSUE TITLE
Random notification dot behavior

### ISSUE THREAD

**Issue by MaCo117** [amirzaidi/Launcher3#403]
First of all, thank you for a wonderful job, I've been happily using this for some time as my daily driver.

I noticed some strange behavior of notification dot on the latest version. It appears on apps randomly, even without active notifications. It disappears and reappears on another app as soon as the app drawer is scrolled or closed. Logcat and screen recording are below.

Screen:
https://photos.app.goo.gl/z1H1B3YVD24m1Fhx1
Logcat:
https://drive.google.com/file/d/18Z3CaD0P4uAyxPYRZ1IyblEPnGnQeMjd/view?usp=drivesdk

I didn't find any donate section anywhere, is there a way to at least buy you a coffee (or whatever else you drink)? Thank you again.

**Comment by amirzaidi** [comment]
Copy paste from my Telegram channel:

I have been researching the "bugged notification dots" too but it seems to be an Android bug that can only be fixed by rebooting the phone. It shouldn't occur unless you update the APK - and if that breaks the dots a reboot should keep it working until the next update. Search "notificationlistenerservice not starting" on Google to find more information, it has been a bug since Android 4.4 and has still not been properly fixed.

Here's a donate link I set up a week ago :)
https://paypal.me/amirzaidi

**Comment by MaCo117** [comment]
Ok, closing the issue then.
Thanks for the link.
