### ISSUE TITLE
No Weather

### ISSUE THREAD

**Issue by Gouster4** [amirzaidi/Launcher3#481]
Hi. Im using release 3.5 on RessurectionRemix rom arm64, device Xperia XZ, soc snapdragon 820.
Weather widget not showing up nexto the date, as it should on pixel launcher.

**Comment by keerthimys** [comment]
Turn on weather updates in your google now feed and your location.

**Comment by fchiacchiaretta** [comment]
Same here, weather updates are active in feed settings and location is active.
If I search "weather" in feed search, I can see weather page of Google app with correct location, but it does not show in widget.
I found a support thread in google pixel forum where users solved this uninstalling updates of Google app in settings (it also clears feed data and settings), indeed after uninstalling weather shows in widget but it disappears again after re-enabling feed updates.

**Comment by jrmribeiro** [comment]
The weather feature is functional, it happened to me at start to but if you give it a reboot it works, also check if you are using an organization email it might not be available.

**Comment by SinkableFish** [comment]
I have the same problem on my nexus 6p with release 3.5. Does google give up supporting this function on Android 8.1 or earlier?

**Comment by amirzaidi** [comment]
Still works for me

**Comment by fchiacchiaretta** [comment]
The issue seems to be related to (maybe buggy) feed configuration, and completely unrelated to launcher.
In the latest version of Google app "at a glance" widget can be added to any launcher as a standalone widget (although still in beta): in my case the standalone widget does not show weather updates too.

**Comment by Robtoms** [comment]
Just updated and I've had this issue aswell, it's not that much of issue coz just replace with Google widget, but upon update to edition, with a Xiaomi Mi A1 8.1 Oreo the weather is non existent, next to the date is blank ? And to be clear this is as I've said it's not a deal breaker, just a commission of issues obtained upon installation. Thanks for your graft, otherwise it's much appreciated. 😉
