### ISSUE TITLE
Nav Bar Color in Search

### ISSUE THREAD

**Issue by thatchrismiller** [amirzaidi/Launcher3#521]
I am currently using an LG G6. I found an APK of this launcher that was updated to work on 18:9 screens.

Found here:
https://www.reddit.com/r/lgg6/comments/8lu9vr/rootless_pixel_launcher_3_working_in_189_for_g6/

Everything works great, except I noticed that when using the search feature (accessed by the dock search bar on the home screen), the nav bar, which is black everywhere else in the UI, is white. Any idea what is causing this?

**Comment by tapr00t** [comment]
I'm using an LG V35 (18:9 screen) and version 3.5 seems to work fine for me.  Whats the problem with 18:9 screens?

**Comment by thatchrismiller** [comment]
On the G6, the nav bar on the home screen is black and not transparent. From what I have read in #498 it's because the app isn't displaying at 18:9. The G6 is forcing it into compatibility mode and it's showing at 16:9 with the black bar at the bottom. And sine the Oreo update, you can only force app scaling on certain apps and the Pixel Launcher isn't one of them.

**Comment by tapr00t** [comment]
The 18:9 screen might not be the issue, because its definitely transparent on my V35.  Although I'm also using the pixel dark theme, that might be affecting it.

**Comment by amirzaidi** [comment]
LG broke the API in Oreo requiring an additional meta tag that SHOULDN'T be in the AndroidManifest.. but I added it anyways in the alphas to fix the black navigation bar for LG Oreo users.

Anyways, the search feature from the dock search bar is completely handled by the Google App. I cannot control whether or not the Google App changes the navigation bar colour to white. From the moment you press the search bar the Google App takes control and shows its UI, that's why the UI randomly changed for a lot of people in a recent update without me doing anything.

**Comment by thatchrismiller** [comment]
Thank you for the reply. That makes total sense. And thanks for taking the time to add the meta tag. LG shouldn't be allowed to write their own code. Their software is a hot mess.

**Comment by amirzaidi** [comment]
LG fix is included in the 3.6 release.
