### ISSUE TITLE
Cannot save changes to 'customize feed' after 3.8.1

### ISSUE THREAD

**Issue by LiddersUK** [amirzaidi/Launcher3#570]
No issues with 3.7 or first release (3.8) on play store, but after the update to 3.8.1 the weather status stopped showing on the home page.
When I checked my Google feed customisations, weather updates is turned off. I cannot turn back on or toggle any other customisations. 

Nexus 5x running Oreo.

**Comment by LiddersUK** [comment]
Removed rootless pixel launcher and bridge. Issue still persists, so unsure at this point if the update is the cause.

**Comment by LiddersUK** [comment]
Clearing Google cache resolved the issue after downgrade to 3.7 but still present on 3.8.1.
If nobody else has this issue will assume it is specific to my phone and close in a couple of days.

**Comment by LiddersUK** [comment]
Customize feed toggles have somehow become reversed. Toggling weather on then back off actually switches it on.
Closing issue as it appears to not be related to pixel launcher.

**Comment by amirzaidi** [comment]
That is a very interesting finding, weird that Google broke it like that..

**Comment by Myron-Biker** [comment]
Also here, Google feed settings not able to safe settings including the weather. Using OnePlus 6. Also 2 friends of mine have same feed problem. One of them using your launcher other does not. I'm questioning if the problem lies in the launcher. Could be Google itself? I'm gonna try and reset Google to check if problem persists.
