### ISSUE TITLE
Disable custom content to left?

### ISSUE THREAD

**Issue by mohsin2596** [amirzaidi/Launcher3#99]
Have you hard coded in the custom content to left? I want to disable it

**Comment by RikKoedoot** [comment]
do you mean the google now page? because that is basicly why you would get
this launcher xD

**Comment by mohsin2596** [comment]
Im trying to make a customized launcher using this as the base

**Comment by jleslie97** [comment]
@mohsin2596 this is based off the stock aosp launcher. You would be better off using that instead.

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mohsin2596** [comment]
@jleslie97 I tried to set a default layout for my launcher using the base aosp code and it just wont work on my test device, amir's repo is the only one working and helping me create a default layout across all my devices ... anyways thanks for the suggestion, I'll see what I can do

**Comment by jleslie97** [comment]
@theDroid25 well if you are simply looking for a cross device layout that you can use on all your devices nova launchers importing and exporting launcher layout feature might interest you. More customisable launcher too. This is just supposed to replicate the pixel launcher for any device. 

If you type launcher 3 into github there are plenty project based from the aosp launcher. Even cyanogenmods launcher is on github atleast a few of them should work fine if your looking to develop your own launcher. I'm not a developer but have seen issue being caused by not keeping android studio up to date when importing projects. Could be as something as simple as that. Hope this helped even if it was a little :) 

Edit: last thing if you install the actual pixel launcher from apkmirror then all the pixel features are disabled on all other devices excluding pixel devices. Just thought I'd mention that too 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RikKoedoot** [comment]
Why the duck would you use a launcher that enabled Google now if you don't
want Google now

**Comment by amirzaidi** [comment]
Yes @theDroid25 it is enabled by default but is easy to disable, take a look at my commit history and revert a few commits (or reset HEAD~commitnumber) to get back to a clean AOSP base

**Comment by currall** [comment]
i would like this feature aswell because the stock pixel launcher has this

**Comment by VincentJoshuaET** [comment]
Use Lawnchair.

**Comment by amirzaidi** [comment]
@currall why don't you just use the regular Pixel Launcher then? If you install it without root it won't have the Google Now panel

**Comment by currall** [comment]
@amirzaidi The pixel launcher apk doesn't have all of the other pixel features enabled like round icons and stuff.

**Comment by amirzaidi** [comment]
Latest version disables the content to the left if you don't have the Google App installed
